# Copy this file to `backend/crates/config/switchboard.toml` or any other
# location referenced by the `SWITCHBOARD_CONFIG` environment variable.
#
# The orchestrator reads these settings at startup. All fields are optional;
# uncomment or adjust entries to match your environment.

[orchestrator]
# default_model = "openrouter/meta-llama/llama-3.1-70b-instruct"
# provider_search_path = ["providers"]

[orchestrator.openrouter]
# REQUIRED: replace with your OpenRouter API key.
api_key = "sk-your-openrouter-api-key"

# Optional overrides
# base_url = "https://openrouter.ai/api/v1"
# request_timeout_seconds = 30
# referer = "https://your-app.example"
# title = "Switchboard NGX"

[database]
# url = "sqlite://switchboard.db"
# max_connections = 10

[auth]
# session_ttl_seconds = 86400

[auth.github]
# client_id = ""
# client_secret = ""
# GitHub OAuth callback example: http://localhost:3000/auth/callback
