-- Axum REST API recipe for crudder
--
-- A generic recipe for generating Rust/Axum HTTP handlers, DTOs, and service traits.
--
-- OPTIONS (set via runner.set_option() or schema annotations):
--   output_dir        - Base output directory (default: "src/generated/rest")
--   models_subdir     - Subdirectory for models (default: "models")
--   traits_subdir     - Subdirectory for traits (default: "traits")
--   api_prefix        - API path prefix for OpenAPI docs (default: "/api/v1")
--   error_module      - Rust module for error types (default: "crate::error")
--   state_type        - Full path to state type (default: "crate::state::GatewayState")
--   models_import     - Use statement for models (default: "crate::rest::models::*")
--   auth_type         - Type extracted by auth middleware (default: "i64")
--   auth_extractor    - Axum extractor for auth (default: "Extension")
--   auth_binding      - Variable name for auth value (default: "user_id")
--
-- Architecture:
-- - Generates a trait for each service (e.g., `MembersServiceTrait`)
-- - Handlers call `state.<service>().<method>()` on the trait implementation
-- - You implement the traits and wire them into your state type
--
-- Conventions:
-- - snake_case field names (no serde rename_all)
-- - @authenticated methods receive the auth extractor
-- - @public methods have no auth requirement

local function opt(ctx, key, default)
  local v = ctx:option(key)
  if v == nil or v == "" then return default end
  return v
end

-- Configurable options with defaults
local function get_config(ctx)
  return {
    output_dir = opt(ctx, "output_dir", "src/generated/rest"),
    models_subdir = opt(ctx, "models_subdir", "models"),
    traits_subdir = opt(ctx, "traits_subdir", "traits"),
    api_prefix = opt(ctx, "api_prefix", "/api/v1"),
    error_module = opt(ctx, "error_module", "crate::error"),
    state_type = opt(ctx, "state_type", "crate::state::GatewayState"),
    models_import = opt(ctx, "models_import", "crate::rest::models::*"),
    auth_type = opt(ctx, "auth_type", "i64"),
    auth_extractor = opt(ctx, "auth_extractor", "Extension"),
    auth_binding = opt(ctx, "auth_binding", "user_id"),
  }
end

local function annotation_arg(annotations, name)
  for _, ann in ipairs(annotations) do
    if ann.name == name then
      return ann.args[1]
    end
  end
  return nil
end

local function module_of_dto(dto)
  return annotation_arg(dto.annotations, "rust_module") or annotation_arg(dto.annotations, "module") or "common"
end

local function module_of_service(service)
  return annotation_arg(service.annotations, "module") or helpers.to_snake_case(service.name:gsub("Service$", ""))
end

local function tag_of_service(service)
  return annotation_arg(service.annotations, "tag") or service.name:gsub("Service$", "")
end

local function router_fn_of_service(service, module)
  return annotation_arg(service.annotations, "router_fn") or ("create_" .. module .. "_routes")
end

local function trait_name_of_service(service)
  return service.name .. "Trait"
end

local function service_accessor_name(service)
  -- e.g., "MembersService" -> "members_service"
  return helpers.to_snake_case(service.name)
end

local function gather_type_imports(schema, dtos)
  local needs_uuid = false
  local needs_chrono = false

  for _, dto in ipairs(dtos) do
    for _, field in ipairs(dto.fields) do
      local base = field.ty:base_type()
      if base.primitive == "uuid" then needs_uuid = true end
      if base.primitive == "timestamp" then needs_chrono = true end
    end
  end

  return needs_uuid, needs_chrono
end

local function emit_models(schema, ctx, config)
  local by_module = {}
  for _, dto in ipairs(schema.dtos) do
    local m = module_of_dto(dto)
    if by_module[m] == nil then by_module[m] = {} end
    table.insert(by_module[m], dto)
  end

  for module, dtos in pairs(by_module) do
    local uses_sqlx = false
    local uses_serialize = false
    local uses_deserialize = false

    for _, dto in ipairs(dtos) do
      if dto:is_entity() then uses_sqlx = true end
      if dto.name:match("Request$") or dto.name:match("Query$") or dto.name:match("Form$") then
        uses_deserialize = true
      else
        uses_serialize = true
      end
    end

    local needs_uuid, needs_chrono = gather_type_imports(schema, dtos)

    local code = helpers.lines()
      :add("// Generated by crudder. DO NOT EDIT.")
      :blank()

    if uses_serialize and uses_deserialize then
      code:add("use serde::{Deserialize, Serialize};")
    elseif uses_deserialize then
      code:add("use serde::Deserialize;")
    elseif uses_serialize then
      code:add("use serde::Serialize;")
    end

    if uses_sqlx then
      code:add("use sqlx::FromRow;")
    end
    code:add("use utoipa::ToSchema;")

    if needs_uuid then
      code:add("use uuid::Uuid;")
    end
    if needs_chrono then
      code:add("use chrono::{DateTime, Utc};")
    end

    code:blank()

    for _, dto in ipairs(dtos) do
      local derives = { "Debug", "ToSchema" }

      if dto.name:match("Request$") or dto.name:match("Query$") or dto.name:match("Form$") then
        table.insert(derives, "Deserialize")
      else
        table.insert(derives, "Serialize")
      end

      if dto:is_entity() then
        table.insert(derives, "FromRow")
        table.insert(derives, "Clone")
      end

      code:add("#[derive(" .. table.concat(derives, ", ") .. ")]")
      code:block("pub struct " .. dto.name .. " {", "}", function(b)
        for _, field in ipairs(dto.fields) do
          local rust_ty = helpers.rust_type(field.ty)
          b:add("pub " .. helpers.to_snake_case(field.name) .. ": " .. rust_ty .. ",")
        end
      end)
      code:blank()
    end

    local out_path = config.output_dir .. "/" .. config.models_subdir .. "/" .. module .. ".rs"
    ctx:emit_file(out_path, code:build())
  end
end

local function openapi_path(api_prefix, path)
  if api_prefix == "" then return path end
  if api_prefix:sub(-1) == "/" and path:sub(1, 1) == "/" then
    return api_prefix:sub(1, -2) .. path
  end
  return api_prefix .. path
end

local function axum_route_path(http_path)
  return string.gsub(http_path, "{([^}]+)}", ":%1")
end

local function method_ident(name)
  return helpers.to_snake_case(name)
end

local function extract_path_params(http_path)
  local params = {}
  for param in string.gmatch(http_path, "{([^}]+)}") do
    table.insert(params, param)
  end
  return params
end

-- Check if a type name indicates it's a query parameter type
local function is_query_type(type_name)
  return type_name and type_name:match("Query$") ~= nil
end

-- Emit the service trait definition
local function emit_service_trait(service, schema, ctx, config)
  local module = module_of_service(service)
  local trait_name = trait_name_of_service(service)

  local code = helpers.lines()
    :add("// Generated by crudder. DO NOT EDIT.")
    :blank()
    :add("use " .. config.error_module .. "::GatewayResult;")
    :add("use " .. config.models_import .. ";")
    :blank()
    :add("/// Service trait for " .. service.name)
    :add("///")
    :add("/// Implement this trait to provide the business logic for the " .. module .. " endpoints.")
    :add("#[allow(async_fn_in_trait)]")
    :add("pub trait " .. trait_name .. ": Send + Sync {")
    :indent()

  for _, method in ipairs(service.methods) do
    local fn_name = method_ident(method.name)
    local http_method_upper = method:http_method() or "GET"
    local http_path = method:http_path() or "/"
    local path_params = extract_path_params(http_path)
    local is_public = method:is_public()

    local has_query = method.input ~= "Empty" and is_query_type(method.input)
    local has_body = (http_method_upper == "POST" or http_method_upper == "PUT" or http_method_upper == "PATCH")
      and method.input ~= "Empty"
      and not is_query_type(method.input)

    local has_output = method.output ~= nil and method.output ~= "Empty"

    -- Build method signature
    local args = { "&self" }
    if not is_public then
      table.insert(args, config.auth_binding .. ": " .. config.auth_type)
    end
    for _, p in ipairs(path_params) do
      table.insert(args, p .. ": String")
    end
    if has_query then
      table.insert(args, "query: " .. method.input)
    end
    if has_body then
      table.insert(args, "req: " .. method.input)
    end

    local return_ty
    if has_output then
      return_ty = "GatewayResult<" .. method.output .. ">"
    else
      return_ty = "GatewayResult<()>"
    end

    code:add("async fn " .. fn_name .. "(" .. table.concat(args, ", ") .. ") -> " .. return_ty .. ";")
    code:blank()
  end

  code:dedent()
  code:add("}")
  code:blank()

  local out_path = config.output_dir .. "/" .. config.traits_subdir .. "/" .. module .. ".rs"
  ctx:emit_file(out_path, code:build())
end

-- Emit the HTTP handlers that call the service trait
local function emit_service_endpoints(service, schema, ctx, config)
  local module = module_of_service(service)
  local tag = tag_of_service(service)
  local trait_name = trait_name_of_service(service)
  local accessor = service_accessor_name(service)

  -- Gather used HTTP methods for imports
  local route_fns = {}
  for _, method in ipairs(service.methods) do
    local http_method = (method:http_method() or "GET"):lower()
    route_fns[http_method] = true
  end

  local routing_imports = {}
  for fn, enabled in pairs(route_fns) do
    if enabled then table.insert(routing_imports, fn) end
  end
  table.sort(routing_imports)

  -- Determine which extractors we need
  local needs_auth = false
  local needs_query = false
  local needs_json = false
  for _, method in ipairs(service.methods) do
    if not method:is_public() then needs_auth = true end
    local http_method_upper = method:http_method() or "GET"
    local has_body = (http_method_upper == "POST" or http_method_upper == "PUT" or http_method_upper == "PATCH") and method.input ~= "Empty"
    if has_body and not is_query_type(method.input) then
      needs_json = true
    end
    -- Also need Json for response bodies
    if method.output ~= nil and method.output ~= "Empty" then
      needs_json = true
    end
    if method.input ~= "Empty" and is_query_type(method.input) then
      needs_query = true
    end
  end

  local extractors = { "Path", "State" }
  if needs_query then
    table.insert(extractors, 1, "Query")
  end
  if needs_auth and config.auth_extractor == "Extension" then
    table.insert(extractors, 1, "Extension")
  end

  local code = helpers.lines()
    :add("// Generated by crudder. DO NOT EDIT.")
    :blank()
    :add("use axum::{")
    :indent()
    :add("extract::{" .. table.concat(extractors, ", ") .. "},")
    :add("routing::{" .. table.concat(routing_imports, ", ") .. "},")
  if needs_json then
    code:add("Json, Router,")
  else
    code:add("Router,")
  end
  code:dedent()
    :add("};")
    :add("use std::sync::Arc;")
    :blank()
    :add("use " .. config.error_module .. "::GatewayResult;")
    :add("use " .. config.models_import .. ";")
    :add("use " .. config.state_type .. ";")
    :add("use crate::generated::rest::traits::" .. module .. "::" .. trait_name .. ";")
    :blank()

  local router_fn = router_fn_of_service(service, module)
  local state_type_name = config.state_type:match("([^:]+)$") or "GatewayState"

  -- Group methods by path to chain handlers properly
  local routes_by_path = {}
  local path_order = {}
  for _, method in ipairs(service.methods) do
    local http_path = method:http_path() or "/"
    local axum_path = axum_route_path(http_path)
    if routes_by_path[axum_path] == nil then
      routes_by_path[axum_path] = {}
      table.insert(path_order, axum_path)
    end
    table.insert(routes_by_path[axum_path], method)
  end

  code:add("pub fn " .. router_fn .. "() -> Router<Arc<" .. state_type_name .. ">> {")
  code:indent()
  code:add("Router::new()")
  code:indent()
  for _, path in ipairs(path_order) do
    local methods = routes_by_path[path]
    local handlers = {}
    for _, method in ipairs(methods) do
      local http_method = (method:http_method() or "GET"):lower()
      table.insert(handlers, http_method .. "(" .. method_ident(method.name) .. ")")
    end
    code:add('.route("' .. path .. '", ' .. table.concat(handlers, ".") .. ')')
  end
  code:dedent()
  code:dedent()
  code:add("}")
  code:blank()

  for _, method in ipairs(service.methods) do
    local fn_name = method_ident(method.name)
    local http_method_upper = method:http_method() or "GET"
    local http_path = method:http_path() or "/"
    local path_params = extract_path_params(http_path)

    local is_public = method:is_public()

    -- Determine input handling
    local has_query = method.input ~= "Empty" and is_query_type(method.input)
    local has_body = (http_method_upper == "POST" or http_method_upper == "PUT" or http_method_upper == "PATCH")
      and method.input ~= "Empty"
      and not is_query_type(method.input)

    local has_output = method.output ~= nil and method.output ~= "Empty"

    local openapi_method = http_method_upper:lower()
    local openapi_p = openapi_path(config.api_prefix, http_path)

    code:add("#[utoipa::path(")
    code:indent()
    code:add(openapi_method .. ",")
    code:add('path = "' .. openapi_p .. '",')
    code:add('tag = "' .. tag .. '",')

    -- OpenAPI params
    local has_utoipa_params = #path_params > 0 or has_query
    if has_utoipa_params then
      code:add("params(")
      code:indent()
      for i, p in ipairs(path_params) do
        local suffix = (i < #path_params or has_query) and "," or ""
        code:add('("' .. p .. '" = String, Path, description = "Path parameter")' .. suffix)
      end
      if has_query then
        code:add(method.input .. ",")
      end
      code:dedent()
      code:add("),")
    end

    if has_body then
      code:add("request_body = " .. method.input .. ",")
    end
    if has_output then
      code:add("responses((status = 200, description = \"OK\", body = " .. method.output .. ")),")
    else
      code:add("responses((status = 200, description = \"OK\")),")
    end
    code:dedent()
    code:add(")]")

    code:add("pub async fn " .. fn_name .. "(")
    code:indent()
    code:add("State(state): State<Arc<" .. state_type_name .. ">>,")
    if not is_public then
      code:add(config.auth_extractor .. "(" .. config.auth_binding .. "): " .. config.auth_extractor .. "<" .. config.auth_type .. ">,")
    end
    if #path_params == 1 then
      code:add("Path(" .. path_params[1] .. "): Path<String>,")
    elseif #path_params > 1 then
      code:add("Path((" .. table.concat(path_params, ", ") .. ")): Path<(" .. string.rep("String, ", #path_params):sub(1, -3) .. ")>,")
    end
    if has_query then
      code:add("Query(query): Query<" .. method.input .. ">,")
    end
    if has_body then
      code:add("Json(req): Json<" .. method.input .. ">,")
    end
    code:dedent()

    local return_ty
    if has_output then
      return_ty = "GatewayResult<Json<" .. method.output .. ">>"
    else
      return_ty = "GatewayResult<()>"
    end
    code:add(") -> " .. return_ty .. " {")
    code:indent()

    -- Build the service call: state.<accessor>().<method>(args)
    local call_args = {}
    if not is_public then
      table.insert(call_args, config.auth_binding)
    end
    for _, p in ipairs(path_params) do
      table.insert(call_args, p)
    end
    if has_query then
      table.insert(call_args, "query")
    end
    if has_body then
      table.insert(call_args, "req")
    end

    local service_call = "state." .. accessor .. "()." .. fn_name .. "(" .. table.concat(call_args, ", ") .. ").await?"

    if has_output then
      code:add("let out = " .. service_call .. ";")
      code:add("Ok(Json(out))")
    else
      code:add(service_call .. ";")
      code:add("Ok(())")
    end
    code:dedent()
    code:add("}")
    code:blank()
  end

  local out_path = config.output_dir .. "/" .. module .. ".rs"
  ctx:emit_file(out_path, code:build())
end

-- Emit the traits mod.rs
local function emit_traits_mod(schema, ctx, config)
  local code = helpers.lines()
    :add("// Generated by crudder. DO NOT EDIT.")
    :blank()

  for _, service in ipairs(schema.services) do
    local module = module_of_service(service)
    code:add("pub mod " .. module .. ";")
  end

  code:blank()

  -- Re-export all traits
  for _, service in ipairs(schema.services) do
    local module = module_of_service(service)
    local trait_name = trait_name_of_service(service)
    code:add("pub use " .. module .. "::" .. trait_name .. ";")
  end

  local out_path = config.output_dir .. "/" .. config.traits_subdir .. "/mod.rs"
  ctx:emit_file(out_path, code:build())
end

return {
  name = "axum-rest",
  description = "Generic Axum REST API endpoints, DTOs, and service traits",
  generate = function(schema, ctx)
    local config = get_config(ctx)

    -- Emit DTOs
    emit_models(schema, ctx, config)

    -- Emit service traits and handlers
    for _, service in ipairs(schema.services) do
      emit_service_trait(service, schema, ctx, config)
      emit_service_endpoints(service, schema, ctx, config)
    end

    -- Emit traits mod.rs
    emit_traits_mod(schema, ctx, config)

    ctx:log("Generated Axum REST endpoints, models, and service traits -> " .. config.output_dir)
  end
}
