-- TypeScript REST client recipe for crudder
--
-- A generic recipe for generating TypeScript types and fetch clients from crudder schemas.
--
-- OPTIONS (set via runner.set_option() or schema annotations):
--   output_dir        - Base output directory for generated files (default: "src/generated")
--   api_prefix        - API path prefix for fetch URLs (default: "/api/v1")
--   auth_header       - Authorization header format (default: "Bearer ${token}")
--   content_type      - Default Content-Type header (default: "application/json")
--
-- Generated files:
-- - <output_dir>/<module>.ts        - TypeScript interfaces for DTOs
-- - <output_dir>/<module>Client.ts  - Typed fetch client functions

local function opt(ctx, key, default)
  local v = ctx:option(key)
  if v == nil or v == "" then return default end
  return v
end

local function get_config(ctx)
  return {
    output_dir = opt(ctx, "output_dir", "src/generated"),
    api_prefix = opt(ctx, "api_prefix", "/api/v1"),
    auth_header = opt(ctx, "auth_header", "Bearer ${token}"),
    content_type = opt(ctx, "content_type", "application/json"),
  }
end

local function annotation_arg(annotations, name)
  for _, ann in ipairs(annotations) do
    if ann.name == name then
      return ann.args[1]
    end
  end
  return nil
end

local function ts_module_of_dto(dto)
  return annotation_arg(dto.annotations, "ts_module") or annotation_arg(dto.annotations, "module") or "common"
end

local function module_of_service(service)
  return annotation_arg(service.annotations, "module") or helpers.to_snake_case(service.name:gsub("Service$", ""))
end

local function ts_type_no_null(ty)
  if ty.kind == "optional" then
    return ts_type_no_null(ty.inner)
  end
  return helpers.ts_type(ty)
end

local function emit_types_by_module(schema, ctx, config)
  local by_module = {}
  for _, dto in ipairs(schema.dtos) do
    local m = ts_module_of_dto(dto)
    if by_module[m] == nil then by_module[m] = {} end
    table.insert(by_module[m], dto)
  end

  for module, dtos in pairs(by_module) do
    table.sort(dtos, function(a, b) return a.name < b.name end)

    local code = helpers.lines()
      :add("// Generated by crudder. DO NOT EDIT.")
      :blank()

    for _, dto in ipairs(dtos) do
      code:block("export interface " .. dto.name .. " {", "}", function(b)
        for _, field in ipairs(dto.fields) do
          local optional = field.ty.kind == "optional" and "?" or ""
          local ts_ty = ts_type_no_null(field.ty)
          b:add(field.name .. optional .. ": " .. ts_ty .. ";")
        end
      end)
      code:blank()
    end

    local out_path = config.output_dir .. "/" .. module .. ".ts"
    ctx:emit_file(out_path, code:build())
  end
end

local function emit_clients(schema, ctx, config)
  local function base_named_type(ty)
    if ty.kind == "named" then
      return ty.name
    end
    if ty.kind == "optional" then
      return base_named_type(ty.inner)
    end
    if ty.kind == "array" then
      return base_named_type(ty.inner)
    end
    return nil
  end

  local function unwrap_return_type(method)
    if method.output == nil or method.output == "Empty" then
      return "void", nil, {}
    end

    local out = schema:get_dto(method.output)
    if out ~= nil and #out.fields == 1 then
      local f = out.fields[1]
      if f.ty.kind == "array" then
        local extra = { method.output }
        local inner = base_named_type(f.ty)
        if inner ~= nil and inner ~= method.output then table.insert(extra, inner) end
        return helpers.ts_type(f.ty), f.name, extra
      end
      if f.ty.kind == "named" then
        local extra = { method.output }
        if f.ty.name ~= method.output then table.insert(extra, f.ty.name) end
        return f.ty.name, f.name, extra
      end
    end

    return method.output, nil, { method.output }
  end

  for _, service in ipairs(schema.services) do
    local module = module_of_service(service)
    local file = config.output_dir .. "/" .. module .. "Client.ts"

    local used_types = {}
    for _, method in ipairs(service.methods) do
      if method.input and method.input ~= "Empty" then
        used_types[method.input] = true
      end
      if method.output and method.output ~= "Empty" then
        local _, _, extra = unwrap_return_type(method)
        for _, t in ipairs(extra) do
          used_types[t] = true
        end
      end
    end

    local imports = {}
    for t, _ in pairs(used_types) do table.insert(imports, t) end
    table.sort(imports)

    local code = helpers.lines()
      :add("// Generated by crudder. DO NOT EDIT.")
      :blank()

    if #imports > 0 then
      code:add('import type { ' .. table.concat(imports, ", ") .. ' } from "./' .. module .. '";')
      code:blank()
    end

    code:add("function authHeaders(token: string): HeadersInit {")
      :indent()
      :add("return {")
      :indent()
      :add('Authorization: `' .. config.auth_header .. '`,')
      :add('"Content-Type": "' .. config.content_type .. '",')
      :dedent()
      :add("};")
      :dedent()
      :add("}")
      :blank()

    -- Helper to check if type is a query type
    local function is_query_type(type_name)
      return type_name and type_name:match("Query$") ~= nil
    end

    for _, method in ipairs(service.methods) do
      local http_method = method:http_method() or "GET"
      local http_path = method:http_path() or "/"
      local fn_name = helpers.to_camel_case(method.name)

      local path_params = {}
      for param in string.gmatch(http_path, "{([^}]+)}") do
        table.insert(path_params, param)
      end

      -- Determine input handling
      local has_query = method.input ~= "Empty" and is_query_type(method.input)
      local has_body = (http_method == "POST" or http_method == "PUT" or http_method == "PATCH")
        and method.input ~= "Empty"
        and not is_query_type(method.input)

      local return_type, unwrap_field = unwrap_return_type(method)

      local params = { "apiBase: string", "token: string" }
      for _, p in ipairs(path_params) do
        table.insert(params, helpers.to_camel_case(p) .. ": string")
      end
      if has_query then
        table.insert(params, "query?: Partial<" .. method.input .. ">")
      end
      if has_body then
        table.insert(params, "data: " .. method.input)
      end

      local url_template = http_path
      for _, p in ipairs(path_params) do
        url_template = string.gsub(url_template, "{" .. p .. "}", "${" .. helpers.to_camel_case(p) .. "}")
      end

      code:add("export async function " .. fn_name .. "(" .. table.concat(params, ", ") .. "): Promise<" .. return_type .. "> {")
      code:indent()

      -- Build URL with query string if needed
      if has_query then
        code:add("const params = new URLSearchParams();")
        code:add("if (query) {")
        code:indent()
        code:add("for (const [key, value] of Object.entries(query)) {")
        code:indent()
        code:add("if (value !== undefined && value !== null) {")
        code:indent()
        code:add("params.set(key, String(value));")
        code:dedent()
        code:add("}")
        code:dedent()
        code:add("}")
        code:dedent()
        code:add("}")
        code:add("const queryString = params.toString();")
        code:add("const url = `${apiBase}" .. config.api_prefix .. url_template .. "${queryString ? '?' + queryString : ''}`;")
      else
        code:add("const url = `${apiBase}" .. config.api_prefix .. url_template .. "`;")
      end

      code:add("const response = await fetch(url, {")
      code:indent()
      code:add('method: "' .. http_method .. '",')
      code:add("headers: authHeaders(token),")
      if has_body then
        code:add("body: JSON.stringify(data),")
      end
      code:dedent()
      code:add("});")
      code:blank()
      code:add("if (!response.ok) {")
      code:indent()
      code:add('throw new Error(`Request failed: ${response.status} ${response.statusText}`);')
      code:dedent()
      code:add("}")

      if return_type == "void" then
        code:dedent()
        code:add("}")
        code:blank()
      else
        code:blank()
        code:add("const json = (await response.json()) as " .. (method.output or "unknown") .. ";")
        if unwrap_field ~= nil then
          code:add("return json." .. unwrap_field .. ";")
        else
          code:add("return json as unknown as " .. return_type .. ";")
        end
        code:dedent()
        code:add("}")
        code:blank()
      end
    end

    ctx:emit_file(file, code:build())
  end
end

return {
  name = "typescript-client",
  description = "Generic TypeScript types + fetch clients",
  generate = function(schema, ctx)
    local config = get_config(ctx)
    emit_types_by_module(schema, ctx, config)
    emit_clients(schema, ctx, config)
    ctx:log("Generated TypeScript types and clients -> " .. config.output_dir)
  end
}
