//! REST API endpoints for the backend

// Centralized DTOs - import these in handlers
pub mod models;

// Service trait implementations
pub mod services;

// Non-generated handlers (streaming endpoints, special cases)
pub mod chat_completion;

// Development-only endpoints
#[cfg(debug_assertions)]
pub mod dev;

use crate::generated::rest as gen;
use crate::state::GatewayState;
use axum::Router;
use std::sync::Arc;

/// Create all REST API routes
pub fn create_rest_routes() -> Router<Arc<GatewayState>> {
    let router = Router::new()
        // Authentication routes (public)
        .merge(gen::create_auth_routes())
        // Health check (public)
        .merge(gen::create_health_routes())
        // Protected routes
        .merge(
            Router::new()
                // Chat completion (streaming, not generated by crudder)
                .merge(chat_completion::create_chat_completion_routes())
                // Chat routes
                .merge(gen::create_chat_routes())
                // Message routes
                .merge(gen::create_message_routes())
                // Invite routes
                .merge(gen::create_invite_routes())
                // Folder routes
                .merge(gen::create_folder_routes())
                // Member routes
                .merge(gen::create_member_routes())
                // Attachment routes
                .merge(gen::create_attachment_routes())
                // Models routes
                .merge(gen::create_models_routes())
                // Notifications routes
                .merge(gen::create_notification_routes())
                // Permissions routes
                .merge(gen::create_permission_routes()),
        );

    // Development-only routes
    #[cfg(debug_assertions)]
    let router = router.merge(dev::create_dev_routes());

    router
}

// Re-export handler types for OpenAPI registration in lib.rs
pub use crate::generated::rest::attachments::{
    create_attachment, delete_attachment, get_attachment, list_attachments,
    list_message_attachments,
};
pub use crate::generated::rest::auth::{github_callback, github_login, logout, me};
#[cfg(debug_assertions)]
pub use dev::dev_token;
pub use crate::generated::rest::chats::{create_chat, delete_chat, get_chat, list_chats, update_chat};
pub use crate::generated::rest::folders::{
    create_folder, delete_folder, get_folder, list_folders, update_folder,
};
pub use crate::generated::rest::health::health_check;
pub use crate::generated::rest::invites::{
    create_invite, delete_invite, get_invite, list_invites, list_user_invites, respond_to_invite,
};
pub use crate::generated::rest::members::{
    get_member, leave_chat, list_members, remove_member, update_member_role,
};
pub use crate::generated::rest::messages::{
    create_message, delete_message, get_message, list_messages, update_message,
};
pub use crate::generated::rest::models::list_models;
pub use crate::generated::rest::notifications::{
    delete_notification, get_notifications, get_unread_count, mark_all_read, mark_notification_read,
};
pub use crate::generated::rest::permissions::{
    create_permission, delete_permission, get_resource_permissions, get_user_permissions,
};
